# -----------------------------------------------------
# Plan Bukkit Configuration file
# More information about each setting:
# https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Configuration
# -----------------------------------------------------
Server:
  ServerName: Plan
# -----------------------------------------------------
Plugin:
  Logging:
    # More information about Locale
    # https://github.com/plan-player-analytics/Plan/wiki/Localization
    Locale: default
    Create_new_locale_file_on_next_enable: false
    Dev: false
    Delete_logs_after_days: 7
  Update_notifications:
    # Display update notification on the website
    Check_for_updates: true
    Notify_about_DEV_releases: false
  Configuration:
    Allow_proxy_to_manage_settings: true
  Frontend_BETA: false
# -----------------------------------------------------
# Supported databases: SQLite, MySQL
# -----------------------------------------------------
Database:
  Type: SQLite
  MySQL:
    Host: localhost
    Port: 3306
    User: root
    Password: minecraft
    Database: Plan
    # Launch options to append after mysql driver address
    Launch_options: "?rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC"
    Max_connections: 8
# -----------------------------------------------------
# More information about SSL Certificate Settings:
# https://github.com/plan-player-analytics/Plan/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
# -----------------------------------------------------
Webserver:
  Port: 8804
  Alternative_IP: false
    # %port% is replaced automatically with Webserver.Port
    Address: your.domain.here:%port%
  # InternalIP usually does not need to be changed, only change it if you know what you're doing!
  # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
  Internal_IP: 0.0.0.0
  Cache:
    Reduced_refresh_barrier: 15
      Unit: SECONDS
    Invalidate_query_results_on_disk_after: 7
      Unit: DAYS
    Invalidate_disk_cache_after: 2
      Unit: DAYS
    Invalidate_memory_cache_after: 5
      Unit: MINUTES
  Security:
    SSL_certificate:
      KeyStore_path: Cert.jks
      Key_pass: default
      Store_pass: default
      Alias: alias
    # HTTPS is required for Login.
    Disable_authentication: false
    # Cross-Origin Resource Sharing (Requests from non-Plan web pages)
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
    CORS:
      Allow_origin: "*"
    # Allows using the whitelist with a reverse-proxy.
    # ! Make sure non-proxy access is not possible, it would allow IP spoofing !
    Use_X-Forwarded-For_Header: false
    IP_whitelist: false
      Whitelist:
        - "192.168.0.0"
        - "0:0:0:0:0:0:0:1"
    # Does not affect existing cookies
    Cookies_expire_after: 2
      Unit: HOURS
  Disable_Webserver: false
  External_Webserver_address: https://www.example.address
# -----------------------------------------------------
Data_gathering:
  Geolocations: true
  # Please accept the EULA to download GeoLite2 IP-Country Database
  # https://www.maxmind.com/en/geolite2/eula
  Accept_GeoLite2_EULA: false
  Ping: true
  Disk_space: true
  Commands:
    Log_unknown: false
    Log_aliases_as_main_command: true
# -----------------------------------------------------
# Supported time units: MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
# -----------------------------------------------------
Time:
  Delays:
    Ping_server_enable_delay: 300
      Unit: SECONDS
    Ping_player_join_delay: 30
      Unit: SECONDS
    Wait_for_DB_Transactions_on_disable: 20
      Unit: SECONDS
  Thresholds:
    # How long player needs to be idle until Plan considers them AFK
    AFK_threshold: 3
      Unit: MINUTES
    # Activity Index considers last 3 weeks and uses these thresholds in the calculation
    # The index is a number from 0 to 5.
    # These numbers were calibrated with data of 250 players (Small sample size).
    Activity_index:
      Playtime_threshold: 30
        Unit: MINUTES
    Remove_inactive_player_data_after: 180
      Unit: DAYS
    # Includes players online, tps and performance time series
    Remove_time_series_data_after: 90
      Unit: DAYS
    Remove_ping_data_after: 14
      Unit: DAYS
    Remove_disabled_extension_data_after: 2
      Unit: DAYS
  Periodic_tasks:
    Extension_data_refresh_every: 1
      Unit: HOURS
    Check_DB_for_server_config_files_every: 1
      Unit: MINUTES
    Clean_Database_every: 1
      Unit: HOURS
# -----------------------------------------------------
Display_options:
  # More information about Themes:
  # https://github.com/plan-player-analytics/Plan/wiki/Themes
  Theme: default
  # Can use ${playerName} or ${playerUUID} or ${playerUUIDNoDash}
  Player_head_image_url: "https://crafatar.com/avatars/${playerUUID}?size=120&default=MHF_Steve&overlay"
  Sessions:
    Show_on_page: 50
    # By Default World playtime pie is ordered alphabetically.
    # Colors will be determined alphabetically in any case.
    Order_world_pies_by_percentage: false
  Players_table:
    Show_on_server_page: 2500
    Show_on_players_page: 25000
  Open_player_links_in_new_tab: false
  Graphs:
    Show_gaps_in_data: false
    TPS:
      High_threshold: 18
      Medium_threshold: 10
    Disk_space:
      High_threshold: 500
      Medium_threshold: 100
  Command_colors:
    Main: '&2'
    Secondary: '&7'
    Highlight: '&f'
# -----------------------------------------------------
Formatting:
  Decimal_points: '#.##'
  Time_amount:
    Year: '1 year, '
    Years: '%years% years, '
    Month: '1 month, '
    Months: '%months% months, '
    Day: '1d '
    Days: '%days%d '
    Hours: '%hours%h '
    Minutes: '%minutes%m '
    Seconds: %seconds%s
    Zero: 0s
  # Dates settings use Java SimpleDateFormat.
  # You can find the patterns & examples here:
  # https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
  Dates:
    # Show_recent_day_names replaces day number with Today, Yesterday, Wednesday etc.
    Show_recent_day_names: true
      # Non-regex pattern to replace
      DatePattern: 'MMM d YYYY'
    Full: 'MMM d YYYY, HH:mm:ss'
    NoSeconds: 'MMM d YYYY, HH:mm'
    JustClock: HH:mm:ss
    # TimeZone Option uses format 'GMT+2' or 'GMT-04:30'
    # Other valid options are 'server' and 'UTC'
    TimeZone: 'server'
# -----------------------------------------------------
# World aliases can be used to rename worlds and to combine multiple worlds into a group.
# -----------------------------------------------------
World_aliases:
  # List of world names: aliases, case sensitive. Set alias of two worlds to same one to group them.
  # Automatically generated, if regex matches world will not be added here.
  List:
    world: world
  # List of - "alias:regex" rules, Set alias of multiple worlds that match regex to group them
  Regex:
    - "Alias for world:^abc$"
# -----------------------------------------------------
# These settings will make Plan write .js, .css, .json and .html files to some location on disk.
# Relative path will render to /plugins/Plan/path
# Make sure user running the server has write permissions to the path.
# On networks export is disabled on Bukkit/Sponge servers.
# -----------------------------------------------------
Export:
  HTML_Export_path: 'Analysis Results'
  JSON_Export_path: 'Raw JSON'
  Parts:
    # Player pages/JSON are only written on join/leave.
    Player_pages: false
    Player_JSON: false
    Players_page: false
    Server_page: false
    Server_JSON: false
  # All player pages/JSON can be exported by using /plan m export players
  Export_player_on_login_and_logout: false
  # If there are multiple servers the period is divided evenly to avoid export of all servers at once
  # Also affects Players page export
  Server_refresh_period: 20
    Unit: MINUTES
# -----------------------------------------------------
# These settings affect Plugin data integration.
# If a plugin is causing issues the integration can be disabled by setting Plugin_name.Enabled: false
# -----------------------------------------------------
Plugins:
  Buycraft:
    # https://docs.tebex.io/store/faq#how-can-i-find-my-secret-key
    Secret: '-'
  Factions:
    HideFactions:
      - ExampleFaction
  Towny:
    HideTowns:
      - ExampleTown
Customized_files:
  Path: "web"
  # Web dev mode enables all customized files and disables webserver resource cache for instant changes on browser refresh.
  Enable_web_dev_mode: false