Settings:
  Locale: default
  UseTextUI: false
  Data:
    GatherLocations: true
  Analysis:
    LogProgressOnConsole: false
    MinutesPlayedUntilConsidiredActive: 10
  Cache:
    Processing:
      GetLimit: 2000
      SaveLimit: 1000
      ClearLimit: 1000
    AnalysisCache:
      RefreshAnalysisCacheOnEnable: true
      RefreshEveryXMinutes: -1
    InspectCache:
      ClearFromInspectCacheAfterXMinutes: 5
    DataCache:
      SaveEveryXMinutes: 2
      ClearCacheEveryXSaves: 5
  WebServer:
    Enabled: true
    Port: 8804
    ShowAlternativeServerIP: false
    AlternativeIP: your.ip.here:%port%
    Security:
      DisplayIPsAndUUIDs: true
      AddressSecurityCode: bAkEd

Customization:
  Colors:
    Commands:
      Main: '&2'
      Secondary: '&7'
      Highlight: '&f'
    HTML:
      ActivityGraph:
        OnlinePlayers: '1E90FF'
        OnlinePlayersFill: '75BBFF'
        NewPlayers: '228B22'
      GamemodePie:
        Survival: '951800'
        Creative: '01A1DB'
        Adventure: '769316'
        Spectator: '228B22'
      ActivityPie:
        Active: '228B22'
        Banned: '951800'
        Inactive: 'A9A9A9'
        JoinedOnce: '808080'
  DemographicsTriggers:
    Trigger: "i'm, am, im, bin"
    Female: 'female, girl, gurl, woman, gal, mrs, she, miss, feminin, weiblich, mädchen, frau'
    Male: 'male, boy, man, boe, sir, mr, guy, he, männlich, maskulin, junge, mann'
    IgnoreWhen: 'sure, think, with, are, you, din'

database:
  type: sqlite
  
mysql:
  host: localhost
  port: 3306
  user: root
  password: minecraft
  database: Plan
