# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Update html-branch

on:
  release:
    types: [ published  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Get git TAG
        id: tagName
        uses: olegtarasov/get-tag@v2.1
      - name: Copy assets ğŸ”§ 
        run: |
          mkdir -p workingdir/Plan/src/main/resources/assets/plan
          cp -r Plan/common/src/main/resources/assets/plan workingdir/Plan/src/main/resources/assets/plan
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: html # The branch the action should deploy to.
          folder: workingdir # The folder the action should deploy.
          commit-message: ${{ steps.tagName.outputs.tag }}
