# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Automatically Deploy Javadocs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Build Javadocs ğŸ”§ 
        run: |
          cd Plan
          echo "Building javadocs with gradle"
          ./gradlew aggregateJavadocs
          echo "Moving to working directory:"
          cd ../
          mkdir javadocs
          mkdir javadocs/all
          mkdir javadocs/api
          cp -r Plan/build/docs/javadoc/* javadocs/all/
          cp -r Plan/api/build/docs/javadoc/* javadocs/api/
          cd javadocs
          touch .nojekyll
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: javadocs # The folder the action should deploy.
    
          
  
